### ISSUE TITLE
Définition d'un combobox dans Browser Automation Studio

### ISSUE THREAD

**Issue by Metsabe** [bablosoft/BAS#14]
I'm using Browser Automation Studio version 26.1.0 to automate my tasks. I don't use code. I have already created a project, added actions and everything works fine. I want the bot to make choices in a dropdown of a field where there are 4 choices. He must click on each choice to choose. You can make 4 choices at a time. The bot is already on the page where there is this field. For the bot to make the first choice I added the following actions: Set Combobox Index and Move And Click On Element. My problem is that the Move And Click On Element action is not working. The bot stops at the Set Combobox Index action. If I execute I have the following information: Success(0)

Fails(1)
Posts:
        1 - [651246774] Failed to wait for element >CSS> #select2-champs-oe-result-g0j4-3

Time Spent: 01:15

Final Message: Too Much Fails. Explain and give the solution.

**Comment by bablosoft** [comment]
We provide support only in English and only by premium email(

https://bablosoft.com/shop/BASPremium
