### ISSUE TITLE
How to automate the following action: pasting text into a field?

### ISSUE THREAD

**Issue by Metsabe** [bablosoft/BAS#15]
I'm using Browser Automation Studio version 26.1.0 to automate my tasks. I don't use code. I have already created a project, added actions and everything works fine. I used the Read cell action to copy text from sheet 3 of cell C4 of my Excel file and paste it into a field on a website. My problem is that if I click the field where the bot should paste the text I don't see the paste action. Can you help me find the paste action.

https://github.com/bablosoft/BAS/assets/117367343/ea5ba19a-2fab-42a2-be3d-9629780fc6ea

**Comment by bablosoft** [comment]
We provide support only by premium email

https://bablosoft.com/shop/BASPremium

**Comment by Metsabe** [comment]
Good morning. With the paid version of Browser Automation Studio, can I
create a bot that pastes an email into the email field of my website?

Le mar. 12 sept. 2023 à 11:14, bablosoft ***@***.***> a
écrit :

**Comment by bablosoft** [comment]
https://bablosoft.com/personal/license/BASPremium - here you can see premium email or skype. Please write question there.
