### ISSUE TITLE
Проблема с отображением текста

### ISSUE THREAD

**Issue by yellowface11** [bablosoft/BAS#17]
Когда я редактирую ресурс, то начинает как-то съезжать текст
у меня подключены 2к и full hd мониторы, возможно проблема из-за этого

https://github.com/bablosoft/BAS/assets/170742098/9640987d-8faa-413d-b55e-df7f7406cc73

**Comment by gegorov2030** [comment]
@yellowface11 код 7 лет как уже забросили, апдейтов не будет.

**Comment by bablosoft** [comment]
> @yellowface11 код 7 лет как уже забросили, апдейтов не будет.

Последняя версия вышла 6 часов назад. Для поддержки пишите на премиум почту.

**Comment by gegorov2030** [comment]
> Последняя версия вышла 6 часов назад. Для поддержки пишите на премиум почту.

Как относится к текущему репо?
