### ISSUE TITLE
Timeout during creating new process

### ISSUE THREAD

**Issue by fdciabdul** [bablosoft/BAS#18]
![image](https://github.com/bablosoft/BAS/assets/31664438/db30a6e2-50b8-4258-97ca-d4f5463b312f)

not sure what happening, download BAS -> Click record.

stuck loading and show error like that.

`[[0]](action://action0) [02:44:26] Thread #1 : Timeout during creating new process`

is that mean my ISP blocked request to BAS server?

**Comment by bablosoft** [comment]
This is fixed in 27.4.1, anyway, please write to premium email.

**Comment by fdciabdul** [comment]
![image](https://github.com/bablosoft/BAS/assets/31664438/fca54cc4-e40c-4cf2-9101-8b4e2269b34e)

im using that version

**Comment by tarnaev** [comment]
> ![image](https://github.com/bablosoft/BAS/assets/31664438/fca54cc4-e40c-4cf2-9101-8b4e2269b34e)
> 
> im using that version

I have the same problem. Have you found a solution?

**Comment by get-n8n** [comment]
та же самая проблема, чистая установка на windows 10

**Comment by moonsoonredt** [comment]
И у меня на 10 винде такая проблема. Систему поставил два дня назад, а бас не может запустить пустой свой стандартный проект.

**Comment by graid2030** [comment]
Forget about it, just use Codex with playwright
