### ISSUE TITLE
Респект создателю ,Вы гений!!!(ki4kin43@yandex.ru) 

### ISSUE THREAD

**Issue by kichkin38** [bablosoft/BAS#2]
Я вообще чайник в этом всём но учится надо.Может есть курсы по программированию?

**Comment by bablosoft** [comment]
Спасибо. Конечно есть, курсов по программированию огромное количество.

**Comment by kichkin38** [comment]
Здравствуйте,ко всему прочему я инвалид 1 гр ,после инсульта,и жить на инвалидскую пенсию не особо возможно.Перерыл весь интернет в поисках ,но тщетно.Пожалуйста помогите.Может курс по яве,или по базам данных.Или тему заработка.Я могу и с Вами что то делать ,как ученик.Я особо не ходок,и посему много у компа сижу.Да и рука одна работает,но многим угнаться будет проблема.Я буду очень благодарен.

**Comment by bablosoft** [comment]
Сочувствую, но я не разбираюсь в курсах. Я готов платить за грамотное продвижение софта, особенно зарубежом. Если вы это умеете - пишите в скайп.

**Comment by kichkin38** [comment]
а по яве програмированию есть? вскайпе тоже bablosoft?

**Comment by bablosoft** [comment]
Я не знаю ни явы, ни курсы по ява программированию.
