### ISSUE TITLE
SSH Proxy Support

### ISSUE THREAD

**Issue by zero77** [bablosoft/BAS#4]
Can you please add SSH proxy support.
Thanks

**Comment by bablosoft** [comment]
Dealing with SSH is not easy thing, for example, need to detect when connection is closed and reconnect.
It is better to keep SSH stuff out of BAS executable. Anyway, you can use that tool https://bablosoft.com/shop/MassTunneler to use SSH with any software including BAS.
Here is e example on how to start/stop MT with BAS. https://www.dropbox.com/s/decjhytgqj0t7xg/MTStartStop.xml?dl=0

**Comment by zero77** [comment]
Thanks, I will have a look.
