### ISSUE TITLE
browser automation studio has problem with pdf documents

### ISSUE THREAD

**Issue by bm2008** [bablosoft/BAS#5]
so here is the issue
its a great simple tool to automate chrome I agree. But it has series issues with websites that Open pdf files in the browser...
when that happens and I try to for example print the document using a javascript code or simply move the mouse to the print button on the plugin BAS fails and closes the thread...

any solution?

**Comment by bablosoft** [comment]
Hi, thanks for report. We will fix it in one of next version. This is no a proper ways to report about issues. In order to submit ticket, please send email to premium email address, which you can find in your personal cabinet.

**Comment by bm2008** [comment]
hello and thank you.
