### ISSUE TITLE
Ошибка 0xc000007b при запуске установщика

### ISSUE THREAD

**Issue by sqdshguy** [bablosoft/BAS#7]
При запуске установщика вылазит окно с ошибкой 0xc000007b. Ошибка пропадает при запуске от имени администратора, но ничего не происходит.
![image](https://user-images.githubusercontent.com/39829869/80527884-c0753900-899d-11ea-80db-0b534108b928.png)

**Comment by bablosoft** [comment]
md5 установщика?

**Comment by sqdshguy** [comment]
Чекнуть не знаю как в винде. Вирустотал показал это: 5c35055a2e79a0b66f6aa0ff75d3d016813ce82e45894991ea0c147a61910189

**Comment by bablosoft** [comment]
Значит что-то с системой или антивирус.
