### ISSUE TITLE
type text missing '@' character

### ISSUE THREAD

**Issue by aselcuk** [bablosoft/BAS#9]
missing @ character on string type text.

original text: testa7939@gmail.com
automation text: testa7939gmail.com   (without '@')

![Untitled](https://user-images.githubusercontent.com/41209531/113363389-68874500-9359-11eb-8a59-2811648e5325.jpg)

engine version: 24.0.3
chrome version: 88.0.4324.190

**Comment by bablosoft** [comment]
This will be fixed in near future(next patch). Meanwhile, you can set English as default keyboard layout.
